#!/bin/sh /etc/rc.common

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root

exec &> /var/log/adblock-oisd.log

START=99
STOP=4

check_oisd_file()
{

	oisd_file_size_KB=`du -bk /tmp/oisd.txt | awk '{print $1}'`

	if [[ $oisd_file_size_KB -ge 20000 ]]; then
		logger -t adblock-oisd "New oisd.txt file size: $oisd_file_size_KB KB too large."
		false
		return
	fi

	rogue_element=`sed '\|^address=|!d;\|/#$|d;q' /tmp/oisd.txt`;

	if [[ ! -z $rogue_element ]]; then
		logger -t adblock-oisd "Rogue element '$rogue_element' identified in new oisd.txt."
		false 
		return
	fi

	true
}


check_dnsmasq()
{
	pgrep -x dnsmasq &> /dev/null
	
	if [[ $? -ne 0 ]]; then
		logger -t adblock-oisd "No instance of dnsmasq detected with new oisd.txt."
		false 
		return
	fi

	for domain in google.com amazon.com microsoft.com
	do
		nslookup $domain | grep -A1 ^Name | grep -q '^Address: *0\.0\.0\.0$'
		if [[ $? -eq 0 ]]; then
			logger -t adblock-oisd "Lookup of '$domain' resulted in 0.0.0.0 with new oisd.txt"
			false
			return
		fi
	done
	
	true
}

start() 
{
	
        for retries in 1 2 3
        do
                wget https://dnsmasq.oisd.nl -O /tmp/oisd.txt &> /dev/null
                [[ $? -eq 0 ]] && break
                sleep 5
	done
	
	if [[ ! -f /tmp/oisd.txt ]]; then
		logger -t adblock-oisd "Download of new oisd.txt file failed."
		return
	fi

	check_oisd_file
	if [[ $? -ne 0 ]]; then
		logger -t adblock-oisd "oisd file check failed with new oisd.txt."
	else
		logger -t adblock-oisd "oisd file check passed with new oisd.txt."
	fi

	sed -i -E '\~^address=/[[:alnum:]][[:alnum:].-]+/#$~!d' /tmp/oisd.txt

	if [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		gzip -c /tmp/dnsmasq.d/oisd.txt > /tmp/prev_oisd.txt.gz
	fi

	mv /tmp/oisd.txt /tmp/dnsmasq.d/oisd.txt

	/etc/init.d/dnsmasq restart &> /dev/null

	sleep 10
	
	check_dnsmasq
	if [[ $? -ne 0 ]]; then
		
		logger -t adblock-oisd "dnsmasq check failed with new oisd.txt file."

		rm /tmp/dnsmasq.d/oisd.txt

		if [[ -f /tmp/prev_oisd.txt.gz ]]; then
			logger -t adblock-oisd "Found previous oisd.txt file. Attempting to recover."
			gunzip -c /tmp/prev_oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
			rm /tmp/prev_oisd.txt.gz

			/etc/init.d/dnsmasq restart &> /dev/null			

			check_dnsmasq
			if [[ $? -ne 0 ]]; then
				logger -t adblock-oisd "dnsmasq check failed with previous oisd.txt file. Stopping adblock-oisd."
				stop
			else
				logger -t adblock-oisd "Previous oisd.txt recovered and dnsmasq check passed."
			fi
		else
			logger -t adblock-oisd "No previous oisd.txt file found. Stopping adblock-oisd"
			stop
		fi
		
	else
		logger -t adblock-oisd "New oisd.txt downloaded and dnsmasq check passed."
		[[ -f /tmp/prev_oisd.txt.gz ]] && rm /tmp/prev_oisd.txt.gz
	fi
}

stop()
{
	[[ -f /tmp/dnsmasq.d/oisd.txt ]] && rm /tmp/dnsmasq.d/oisd.txt
	/etc/init.d/dnsmasq restart &> /dev/null
}
