#!/bin/sh /etc/rc.common

# adblock-oisd blocks ads using the highly popular oisd dnsmasq file and
# offers a simpler solution to adblocking than the bloated alternatives on OpenWrt

# Project homepage: https://github.com/lynxthecat/adblock-oisd

# Authors: @Lynx and @Wizballs (OpenWrt forum)

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root

START=99
STOP=4

EXTRA_COMMANDS="status pause resume"
EXTRA_HELP="	
	adblock-oisd custom commands:
	status		check dnsmasq and good line count of existing oisd.txt
	pause		pause adblock-oisd
	resume		resume adblock-oisd"

log_msg()
{
	local msg=${1}
	printf "${msg}\n"
	logger -t adblock-oisd "${msg}"
}

check_oisd_file()
{
	log_msg "Checking new oisd.txt."

	oisd_file_size_KB=`du -bk /tmp/oisd.txt | awk '{print $1}'`

	if [[ ${oisd_file_size_KB} -ge 20000 ]]; then
		log_msg "New oisd.txt file size: ${oisd_file_size_KB} KB too large."
		false
		return
	fi

	# Clean whitespace
	sed -i '\~^\s*$~d;s/^[ \t]*//;s/[ \t]*$//' /tmp/oisd.txt

	# Get line number and match of any rogue elements
	rogue_element=`sed -nE '\~(^address=/|^server=/|^local=/)[[:alnum:]][[:alnum:].-]+(/$|/#$)|^#|^\s*$~d;{p;=;q}' /tmp/oisd.txt | { read match; read line; [[ ! -z ${match} ]] && echo "${line}: ${match}"; }`

	if [[ ! -z "${rogue_element}" ]]; then
		log_msg "Rogue element: '${rogue_element}' identified in new oisd.txt."
		false 
		return
	fi

	good_line_count=`sed '\|^#|d;\|^\s*$|d' /tmp/oisd.txt | wc -l`

	if [[ ${good_line_count} -lt 100000 ]]; then
		log_msg "Good line count: ${good_line_count} below 100,000."
		false
		return
	fi

	true
}


check_dnsmasq()
{
	log_msg "Checking dnsmasq instance."

	pgrep -x dnsmasq &> /dev/null
	
	if [[ ${?} -ne 0 ]]; then
		log_msg "No instance of dnsmasq detected with new oisd.txt."
		false 
		return
	fi

	for domain in google.com amazon.com microsoft.com
	do
		nslookup ${domain} | grep -A1 ^Name | grep -q '^Address: *0\.0\.0\.0$'
		if [[ ${?} -eq 0 ]]; then
			log_msg "Lookup of '${domain}' resulted in 0.0.0.0 with new oisd.txt"
			false
			return
		fi
	done
	
	true
}

start() 
{

	log_msg "Started adblock-oisd."

	if [[ "${RANDOM_DELAY}" == "1" ]]; then
		random_delay_mins=$(($(hexdump -n 1 -e '"%u"' </dev/urandom)%60))
		log_msg "Delaying download by ${random_delay_mins} minutes (thundering herd prevention)."
		sleep "${random_delay_mins}m"
	fi

	log_msg "Downloading new oisd.txt."
	
        for retries in 1 2 3
        do
                wget https://dnsmasq2.oisd.nl -O /tmp/oisd.txt &> /dev/null
                if [[ ${?} -eq 0 ]]; then
			log_msg "Download of new oisd.txt file suceeded."
			break
		fi
	
                sleep 5
	done
	
	if [[ ! -f /tmp/oisd.txt ]]; then
		log_msg "Download of new oisd.txt file failed."
		return
	fi


	check_oisd_file
	if [[ ${?} -ne 0 ]]; then
		log_msg "New oisd.txt file check failed."
		exit
	else
		log_msg "New oisd.txt file check passed."
	fi

	if [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		gzip -c /tmp/dnsmasq.d/oisd.txt > /tmp/prev_oisd.txt.gz
	fi

	mv /tmp/oisd.txt /tmp/dnsmasq.d/oisd.txt

	log_msg "Restarting dnsmasq."

	/etc/init.d/dnsmasq restart &> /dev/null

	sleep 10
	
	check_dnsmasq
	if [[ ${?} -ne 0 ]]; then
		
		log_msg "The dnsmasq check failed with new oisd.txt file."

		rm /tmp/dnsmasq.d/oisd.txt

		if [[ -f /tmp/prev_oisd.txt.gz ]]; then
			log_msg "Found previous oisd.txt file. Attempting to recover."
			gunzip -c /tmp/prev_oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
			rm /tmp/prev_oisd.txt.gz

			/etc/init.d/dnsmasq restart &> /dev/null			

			check_dnsmasq
			if [[ ${?} -ne 0 ]]; then
				log_msg "The dnsmasq check failed with previous oisd.txt file. Stopping adblock-oisd."
				stop
			else
				log_msg "Previous oisd.txt recovered and dnsmasq check passed."
			fi
		else
			log_msg "No previous oisd.txt file found. Stopping adblock-oisd"
			stop
		fi
		
	else
		log_msg "The dnsmasq check passed with new oisd.txt file."
		log_msg "New oisd.txt installed with good line count: ${good_line_count}."
		[[ -f /tmp/prev_oisd.txt.gz ]] && rm /tmp/prev_oisd.txt.gz
	fi
}

stop()
{
	log_msg "Stopping adblock-oisd." 
	log_msg "Removing /tmp/dnsmasq.d/oisd.txt and restarting dnsmasq."
	[[ -f /tmp/dnsmasq.d/oisd.txt ]] && rm /tmp/dnsmasq.d/oisd.txt
	/etc/init.d/dnsmasq restart &> /dev/null
	log_msg "Stopped adblock-oisd."
}

status()
{
	if ! [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		log_msg "No /tmp/dnsmasq.d/oisd.txt identified."
		log_msg "adblock-oisd is not active."
	fi
	check_dnsmasq
	if [[ ${?} -ne 0 ]]; then
		log_msg "The dnsmasq check failed with existing oisd.txt file."
	else
		good_line_count=`sed '\|^#|d;\|^\s*$|d' /tmp/dnsmasq.d/oisd.txt | wc -l`
		log_msg "The dnsmasq check passed and the presently installed oisd.txt has good line count: ${good_line_count}."
		log_msg "adblock-oisd appears to be active."
	fi
}

pause()
{
	log_msg "Received pause request."
	if [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		log_msg "Saving /tmp/dnsmasq.d/oisd.txt as /tmp/oisd.txt.gz."
		gzip -c /tmp/dnsmasq.d/oisd.txt > /tmp/oisd.txt.gz
		rm /tmp/dnsmasq.d/oisd.txt
		log_msg "Restarting dnsmasq."
		/etc/init.d/dnsmasq restart &> /dev/null
		log_msg "adblock-oisd is now paused."
	else
		log_msg "No active /tmp/dnsmasq.d/oisd.txt identified."
	fi
}

resume()
{
	log_msg "Received resume request."
	if [[ -f /tmp/oisd.txt.gz ]]; then
		log_msg "Restoring saved /tmp/oisd.txt.gz to /tmp/dnsmasq.d/oisd.txt"
		gunzip -c /tmp/oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
		rm /tmp/oisd.txt.gz
		log_msg "Restarting dnsmasq."
		/etc/init.d/dnsmasq restart &> /dev/null
		log_msg "adblock-oisd is now active."
	else
		log_msg "No stored /tmp/oisd.txt.gz identified."
	fi	
}
