#!/bin/sh /etc/rc.common

# adblock-oisd blocks ads using the highly popular oisd dnsmasq file and
# offers a simpler solution to adblocking than the bloated alternatives on OpenWrt

# Project homepage: https://github.com/lynxthecat/adblock-oisd

# Authors: @Lynx and @Wizballs (OpenWrt forum)

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root

START=99
STOP=4

EXTRA_COMMANDS="pause resume"
EXTRA_HELP="	
	adblock-oisd custom commands:
	pause		pause adblock-oisd
	resume		resume adblock-oisd"

check_oisd_file()
{
	exec &> /var/log/adblock-oisd.log

	oisd_file_size_KB=`du -bk /tmp/oisd.txt | awk '{print $1}'`

	if [[ $oisd_file_size_KB -ge 20000 ]]; then
		logger -t adblock-oisd "New oisd.txt file size: $oisd_file_size_KB KB too large."
		false
		return
	fi

	# Clean whitespace
	sed -i '\~^\s*$~d;s/^[ \t]*//;s/[ \t]*$//' /tmp/oisd.txt

	# Get line number and match of any rogue elements
	rogue_element=`sed -nE '\~(^address=/|^server=/)[[:alnum:]][[:alnum:].-]+(/$|/#$)|^#|^\s*$~d;{p;=;q}' /tmp/oisd.txt | { read match; read line; [[ ! -z $match ]] && echo "$line: $match"; }`

	if [[ ! -z "$rogue_element" ]]; then
		logger -t adblock-oisd "Rogue element: '$rogue_element' identified in new oisd.txt."
		false 
		return
	fi

	good_line_count=`sed '\|^#|d;\|^\s*$|d' /tmp/oisd.txt | wc -l`

	if [[ $good_line_count -lt 100000 ]]; then
		logger -t adblock-oisd "Good line count: $good_line_count below 100,000."
		false
		return
	fi

	true
}


check_dnsmasq()
{
	exec &> /var/log/adblock-oisd.log

	pgrep -x dnsmasq &> /dev/null
	
	if [[ $? -ne 0 ]]; then
		logger -t adblock-oisd "No instance of dnsmasq detected with new oisd.txt."
		false 
		return
	fi

	for domain in google.com amazon.com microsoft.com
	do
		nslookup $domain | grep -A1 ^Name | grep -q '^Address: *0\.0\.0\.0$'
		if [[ $? -eq 0 ]]; then
			logger -t adblock-oisd "Lookup of '$domain' resulted in 0.0.0.0 with new oisd.txt"
			false
			return
		fi
	done
	
	true
}

start() 
{

	logger -t adblock-oisd "Started adblock-oisd."

	if [[ "$RANDOM_DELAY" == "1" ]]; then
		random_delay_mins=$(($(hexdump -n 1 -e '"%u"' </dev/urandom)%60))
		logger -t adblock-oisd "Delaying download by $random_delay_mins minutes (thundering herd prevention)."
		sleep "${random_delay_mins}m"
	fi
	
        for retries in 1 2 3
        do
                wget https://dnsmasq.oisd.nl -O /tmp/oisd.txt &> /dev/null
                if [[ $? -eq 0 ]]; then
			logger -t adblock-oisd "Download of new oisd.txt file suceeded."
			break
		fi
	
                sleep 5
	done
	
	if [[ ! -f /tmp/oisd.txt ]]; then
		logger -t adblock-oisd "Download of new oisd.txt file failed."
		return
	fi

	check_oisd_file
	if [[ $? -ne 0 ]]; then
		logger -t adblock-oisd "oisd file check failed with new oisd.txt."
		exit
	else
		logger -t adblock-oisd "oisd file check passed with new oisd.txt."
	fi

	if [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		gzip -c /tmp/dnsmasq.d/oisd.txt > /tmp/prev_oisd.txt.gz
	fi

	mv /tmp/oisd.txt /tmp/dnsmasq.d/oisd.txt

	/etc/init.d/dnsmasq restart &> /dev/null

	sleep 10
	
	check_dnsmasq
	if [[ $? -ne 0 ]]; then
		
		logger -t adblock-oisd "dnsmasq check failed with new oisd.txt file."

		rm /tmp/dnsmasq.d/oisd.txt

		if [[ -f /tmp/prev_oisd.txt.gz ]]; then
			logger -t adblock-oisd "Found previous oisd.txt file. Attempting to recover."
			gunzip -c /tmp/prev_oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
			rm /tmp/prev_oisd.txt.gz

			/etc/init.d/dnsmasq restart &> /dev/null			

			check_dnsmasq
			if [[ $? -ne 0 ]]; then
				logger -t adblock-oisd "dnsmasq check failed with previous oisd.txt file. Stopping adblock-oisd."
				stop
			else
				logger -t adblock-oisd "Previous oisd.txt recovered and dnsmasq check passed."
			fi
		else
			logger -t adblock-oisd "No previous oisd.txt file found. Stopping adblock-oisd"
			stop
		fi
		
	else
		logger -t adblock-oisd "New oisd.txt installed with line count: $good_line_count and dnsmasq check passed."
		[[ -f /tmp/prev_oisd.txt.gz ]] && rm /tmp/prev_oisd.txt.gz
	fi
}

stop()
{
	[[ -f /tmp/dnsmasq.d/oisd.txt ]] && rm /tmp/dnsmasq.d/oisd.txt
	/etc/init.d/dnsmasq restart &> /dev/null
}

pause()
{
	logger -t adblock-oisd "Received pause request."
	if [[ -f /tmp/dnsmasq.d/oisd.txt ]]; then
		gzip -c /tmp/dnsmasq.d/oisd.txt > /tmp/oisd.txt.gz
		rm /tmp/dnsmasq.d/oisd.txt
		/etc/init.d/dnsmasq restart &> /dev/null
		logger -t adblock-oisd "/tmp/dnsmasq.d/oisd.txt temporarily saved as /tmp/oisd.txt.gz and dnsmasq restarted."
	else
		logger -t adblock-oisd "No active /tmp/dnsmasq.d/oisd.txt identified."
	fi
}

resume()
{
	logger -t adblock-oisd "Received resume request."
	if [[ -f /tmp/oisd.txt.gz ]]; then
		gunzip -c /tmp/oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
		rm /tmp/oisd.txt.gz
		/etc/init.d/dnsmasq restart &> /dev/null
		logger -t adblock-oisd "/tmp/oisd.txt.gz uncompressed and written back to /tmp/dnsmasq.d/ and dnsmasq restarted."
	else
		logger -t adblock-oisd "No stored /tmp/oisd.txt.gz identified."
	fi	
}
